//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace MetroHangman.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("MetroHangman.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    the
        ///   be
        ///   and
        ///   of
        ///   a
        ///   in
        ///   to
        ///   have
        ///   to
        ///   it
        ///   I
        ///   that
        ///   for
        ///   you
        ///   he
        ///   with
        ///   on
        ///   do
        ///   say
        ///   this
        ///   they
        ///   at
        ///   but
        ///   we
        ///   his
        ///   from
        ///   that
        ///   not
        ///   n&apos;t
        ///   n&apos;t
        ///   by
        ///   she
        ///   or
        ///   as
        ///   what
        ///   go
        ///   their
        ///   can
        ///   who
        ///   get
        ///   if
        ///   would
        ///   her
        ///   all
        ///   my
        ///   make
        ///   about
        ///   know
        ///   will
        ///   as
        ///   up
        ///   one
        ///   time
        ///   there
        ///   year
        ///   so
        ///   think
        ///   when
        ///   which
        ///   them
        ///   some
        ///   me
        ///   people
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Common_Words {
            get {
                return ResourceManager.GetString("Common_Words", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abruptly 
        ///affix 
        ///askew 
        ///axiom 
        ///azure 
        ///bagpipes 
        ///bandwagon 
        ///banjo 
        ///bayou 
        ///bikini 
        ///blitz 
        ///bookworm 
        ///boxcar 
        ///boxful 
        ///buckaroo 
        ///buffalo 
        ///buffoon 
        ///cobweb 
        ///croquet 
        ///daiquiri 
        ///disavow 
        ///duplex 
        ///dwarves 
        ///equip 
        ///exodus 
        ///fishhook 
        ///fixable 
        ///foxglove 
        ///galaxy 
        ///galvanize 
        ///gazebo 
        ///gizmo 
        ///glowworm 
        ///guffaw 
        ///haiku 
        ///haphazard 
        ///hyphen 
        ///icebox 
        ///injury 
        ///ivory 
        ///ivy 
        ///jaundice 
        ///jawbreaker 
        ///jaywalk 
        ///jazzy 
        ///jigsaw 
        ///jiujitsu 
        ///jockey 
        ///jovial 
        ///joyful 
        ///juicy 
        ///jumbo 
        ///kazoo 
        ///keyhole 
        ///kha [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Harder_Words {
            get {
                return ResourceManager.GetString("Harder_Words", resourceCulture);
            }
        }
    }
}
