//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Configuration;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using MetroFramework;

namespace MetroHangman.Properties {
    
    
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Default")]
        public MetroColorStyle Theme {
            get {
                return ((MetroColorStyle)(this["Theme"]));
            }
            set {
                this["Theme"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool DiscoOn {
            get {
                return ((bool)(this["DiscoOn"]));
            }
            set {
                this["DiscoOn"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0")]
        public int commonwins {
            get {
                return ((int)(this["commonwins"]));
            }
            set {
                this["commonwins"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0")]
        public int commonlosses {
            get {
                return ((int)(this["commonlosses"]));
            }
            set {
                this["commonlosses"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0")]
        public int hardwins {
            get {
                return ((int)(this["hardwins"]));
            }
            set {
                this["hardwins"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0")]
        public int hardlosses {
            get {
                return ((int)(this["hardlosses"]));
            }
            set {
                this["hardlosses"] = value;
            }
        }
    }
}
